### ISSUE TITLE
undefined method `redisplay_progressbar' for Fog::Formatador:Class

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-core#121]
@davehatton:

> After upgrading from 1.25 to 1.27 the following error

> undefined method `redisplay_progressbar' for Fog::Formatador:Class

> is generated by fog-1.27.0/lib/fog/vcloud_director/models/compute/task.rb

> The problem occurs when calling fog from the vcloud-tools gem when creating a new VM in a vcloud_director/Skyscape environment.

> Downgrading to 1.25 resolves the issue.

Opened at fog/fog#3398

**Comment by geemus** [comment]
I believe this should be closed by https://github.com/fog/fog-core/commit/58556e4b1e65d2ac8dd177c531dd8a23929d39e3

**Comment by plribeiro3000** [comment]
@geemus i was about to do that. =)
